Revert "7096-try using bare metal to run tests in ms hosted build agent"
This reverts commit a74cce155257f36dc93dc9219ed947c2532ac725.

diff --git a/Dev/.azure/pipeline.yml b/Dev/.azure/pipeline.yml
--- a/Dev/.azure/pipeline.yml
+++ b/Dev/.azure/pipeline.yml
@@ -13,6 +13,8 @@ jobs:
 
 - job: build
   displayName: 'Compile'
+  pool:
+    vmImage: 'windows-2022'
 
   steps:
   - task: PowerShell@2
@@ -20,22 +22,22 @@ jobs:
       filePath: '$(Agent.BuildDirectory)/s/Compile.ps1'
       arguments: '-AcceptanceTesting -MSBuildPath "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\MSBuild.exe"'
 
-  - script: "\"$(Agent.BuildDirectory)/s/bin/AcceptanceTesting/Job Shortcuts/Bare Metal/Other Unit Tests.bat\""
-    displayName: 'Run Tests'
+#  - script: "\"$(Agent.BuildDirectory)/s/bin/AcceptanceTesting/Job Shortcuts/Bare Metal/Other Unit Tests.bat\""
+#    displayName: 'Run Tests'
 
-  - task: PublishTestResults@2
-    inputs:
-      testRunner: VSTest
-      testResultsFiles: '$(Agent.BuildDirectory)/s/bin/AcceptanceTesting/TestResults/*.trx'
-      failTaskOnFailedTests: true
-      testRunTitle: 'Unit Tests'
-     
-  - script: 'if not exist "$(Agent.BuildDirectory)/s/bin/AcceptanceTesting/TestResults/*.trx" exit 1'
+#  - task: PublishTestResults@2
+#    inputs:
+#      testRunner: VSTest
+#      testResultsFiles: '$(Agent.BuildDirectory)/s/bin/AcceptanceTesting/TestResults/*.trx'
+#      failTaskOnFailedTests: true
+#      testRunTitle: 'Unit Tests'
+      
+#  - script: 'if not exist "$(Agent.BuildDirectory)/s/bin/AcceptanceTesting/TestResults/*.trx" exit 1'
 
-  - task: DeleteFiles@1
-    inputs:
-      SourceFolder: '$(Agent.BuildDirectory)\\s\\bin\\AcceptanceTesting'
-      Contents: 'TestResults'
+#  - task: DeleteFiles@1
+#    inputs:
+#      SourceFolder: '$(Agent.BuildDirectory)\\s\\bin\\AcceptanceTesting'
+#      Contents: 'TestResults'
 
   - script: |
       docker login --username ashley.lewis@theunlimited.co.za --password %PushVSTestContainer% registry.gitlab.com/warewolf/vstest
@@ -185,15 +187,17 @@ jobs:
     vmImage: 'windows-2022'
 
   steps:
-  - task: PowerShell@2
-    inputs:
-      filePath: '$(Agent.BuildDirectory)\s\Compile.ps1'
-      arguments: '-AcceptanceTesting -MSBuildPath "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\MSBuild.exe"'
-      
-  - powershell: |
-      Set-Location "$(Agent.BuildDirectory)\s\bin\AcceptanceTesting"
-      &"$(Agent.BuildDirectory)\s\bin\AcceptanceTesting\Job Shortcuts\TestRun.ps1" -RetryCount 6 -Projects Warewolf.Studio.ViewModels.Tests -Category RequestServiceNameViewModel
+  - checkout: none
+
+  - script: |
+      docker login --username ashley.lewis@theunlimited.co.za --password %GetVSTestContainer% registry.gitlab.com/warewolf/vstest
+      mkdir "$(Agent.BuildDirectory)\TestResults"
+      echo Set-Location C:\BuildUnderTest>"$(Agent.BuildDirectory)\TestResults\RunTestsEntrypoint.ps1"
+      echo ^&".\Job Shortcuts\TestRun.ps1" -RetryCount 6 -Projects Warewolf.Studio.ViewModels.Tests -Category RequestServiceNameViewModel>>"$(Agent.BuildDirectory)\TestResults\RunTestsEntrypoint.ps1"
+      docker run -i --rm --memory 4g -v "$(Agent.BuildDirectory)\TestResults:C:\BuildUnderTest\TestResults" registry.gitlab.com/warewolf/vstest:$(Build.SourceVersion) powershell -File C:\BuildUnderTest\TestResults\RunTestsEntrypoint.ps1
     displayName: 'Run Tests'
+    env:
+      GetVSTestContainer: $(VSTestContainerPassword)
 
   - task: PublishTestResults@2
     inputs:
